USE [master]
GO

CREATE DATABASE [DWH]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DWH', FILENAME = N'D:\PCT_DB\Database\DWH.mdf' , SIZE = 20426432KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DWH_log', FILENAME = N'D:\PCT_DB\Database\DWH_log.ldf' , SIZE = 3480448KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DWH] SET COMPATIBILITY_LEVEL = 110 
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DWH].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DWH] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DWH] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DWH] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DWH] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DWH] SET ARITHABORT OFF 
GO

ALTER DATABASE [DWH] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DWH] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DWH] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DWH] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DWH] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DWH] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DWH] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DWH] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DWH] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DWH] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DWH] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DWH] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DWH] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DWH] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DWH] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DWH] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DWH] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DWH] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DWH] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DWH] SET  MULTI_USER 
GO

ALTER DATABASE [DWH] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DWH] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DWH] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DWH] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DWH] SET  READ_WRITE 
GO


--Создание схем БД
use DWH
go

CREATE SCHEMA [DDS]
GO

CREATE SCHEMA [CONV]
GO

CREATE SCHEMA [PREDDS]
GO

CREATE SCHEMA [MDSCONV]
GO




